language: ruby
cache: bundler
sudo: false
services:
- mongodb
- elasticsearch
rvm:
- 2.1.4
notifications:
  irc:
    channels:
    - irc.freenode.net#openaddresses
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
env:
  global:
    - secure: e+4d+AekfbT0XxjqWLms55l76Q1vMyfXdSnujb1YBv8ZrI0yo3z+Qk5YQjQacK7JhECYC/L2mfjBHLKc6gsHFOaJdftAz7cFLsqAJ74afQpt9pSI3bQV3pk5NZocgX05VKF6rnTyiDHT8ExEyZGDPmEFZKONiAVz6XUfpaiAP5s=
    - AWS_ACCESS_KEY=asdasdasdasd
    - AWS_SECRET_ACCESS_KEY=sfsdfdsfsdfdsfsdfsfsd
    - AWS_BUCKET=test.openaddressesuk.org
    - GA_TRACKER_ID=dsfsdfsd
    - GA_DOMAIN=dsdsfsfs
    - BUGHERD_PROJECT_KEY=dsfdsfsdsdf
    - OPENSPACE_API_KEY=dsfsdfdsfs
    - LEGATO_OAUTH_REFRESH_TOKEN=thisisfake
    - LEGATO_OAUTH_CLIENT_ID=fdsfdsdsfs
    - LEGATO_OAUTH_SECRET_KEY=dsfsdfsdfsfsd
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: CJrk6UhdbltH1eFJzlBTftZmnnYRGfYEhQOy/g5ORcoUwk8mUpU1YgCqa2e9qbPUHszM9ASYM4x16EEHlhM6bTfgTm+Rmbwe4d0Tbvtc/+kn6uFXjr98LQVxKWFoidqEfjihqnbDKpElDaT0gJqVUrua7XVTCgjPxJgy0S/4RIw=
  app: oa-theodolite
  on:
    repo: OpenAddressesUK/theodolite
